site_name:           Parameters.jl
repo_url:            https://github.com/mauro3/Parameters.jl
site_description:    Types with default field values, keyword constructors and (un-)pack macros
site_author:         Mauro Werder
theme:               readthedocs
markdown_extensions: [tables, fenced_code]
pages:
- Introduction: index.md
- Manual: manual.md
- API: api/Parameters.md
- API Index: api/index.md
